// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackLinks: typeof import('./src/components/BackLinks.vue')['default']
    BackTop: typeof import('./src/components/BackTop.vue')['default']
    BackToTop: typeof import("./src/components/BackTop.vue")["default"]
    Category: typeof import('./src/components/Category.vue')['default']
    copy: typeof import("./src/components/Header copy.vue")["default"]
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import("element-plus/es")["ElButton"]
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import("element-plus/es")["ElDropdown"]
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"]
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"]
    ElFooter: typeof import("element-plus/es")["ElFooter"]
    ElHeader: typeof import("element-plus/es")["ElHeader"]
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadio: typeof import("element-plus/es")["ElRadio"]
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"]
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"]
    IconCommunity: typeof import("./src/components/icons/IconCommunity.vue")["default"]
    IconDocumentation: typeof import("./src/components/icons/IconDocumentation.vue")["default"]
    IconEcosystem: typeof import("./src/components/icons/IconEcosystem.vue")["default"]
    IconSupport: typeof import("./src/components/icons/IconSupport.vue")["default"]
    IconTooling: typeof import("./src/components/icons/IconTooling.vue")["default"]
    LastUpdate: typeof import('./src/components/LastUpdate.vue')['default']
    MenuItem: typeof import("./src/components/MenuItem.vue")["default"]
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    PopularArticles: typeof import('./src/components/PopularArticles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Social: typeof import('./src/components/Social.vue')['default']
    SubMenu: typeof import("./src/components/NavMenu.vue")["default"]
    SubMenuMobile: typeof import("./src/components/SubMenuMobile.vue")["default"]
    TheWelcome: typeof import("./src/components/TheWelcome.vue")["default"]
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    WelcomeItem: typeof import("./src/components/WelcomeItem.vue")["default"]
  }
}
